### ISSUE TITLE
Unable to do "import pympler.muppy" on PyPy due to AttributeError

### ISSUE THREAD

**Issue by sakurai-youhei** [pympler/pympler#34]
*0.4.3: pympler doesn't work on PyPy*
```
[ec2-user@i-89b56b16 ~]$ /opt/pypy/bin/pypy -c "import pympler.muppy"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/pypy/site-packages/pympler/muppy.py", line 15, in <module>
    from pympler.asizeof import _Py_TPFLAGS_HAVE_GC
  File "/opt/pypy/site-packages/pympler/asizeof.py", line 206, in <module>
    _sizeof_Cdigit = long.__itemsize__
AttributeError: type object 'long' has no attribute '__itemsize__'
[ec2-user@i-89b56b16 ~]$ /opt/pypy/bin/pypy --version
Python 2.7.10 (5f8302b8bf9f53056e40426f10c72151564e5b19, Nov 19 2015, 13:36:43)
[PyPy 4.0.1 with GCC 4.9.2]
[ec2-user@i-89b56b16 ~]$ git clone https://github.com/pympler/pympler.git
Cloning into 'pympler'...
remote: Counting objects: 2499, done.
remote: Compressing objects: 100% (25/25), done.
remote: Total 2499 (delta 7), reused 0 (delta 0), pack-reused 2473
Receiving objects: 100% (2499/2499), 975.76 KiB | 558.00 KiB/s, done.
Resolving deltas: 100% (1395/1395), done.
Checking connectivity... done.
[ec2-user@i-89b56b16 ~]$ cd pympler/
[ec2-user@i-89b56b16 pympler]$ /opt/pypy/bin/pypy setup.py try
running try
/opt/pypy/bin/pypy test/runtest.py -pre-install -verbose 3
Python 2.7.10 (5f8302b8bf9f53056e40426f10c72151564e5b19, Nov 19 2015, 13:36:43)
64-bit [PyPy 4.0.1 with GCC 4.9.2]

Traceback (most recent call last):
  File "test/runtest.py", line 136, in <module>
    tst, all = suite(dirs, clean=clean, pre=pre, verbose=verbose)
  File "test/runtest.py", line 70, in suite
    mod = __import__(test, globals(), locals(), [mod])
  File "/home/ec2-user/pympler/test/muppy/test_muppy.py", line 6, in <module>
    import pympler.muppy
  File "/home/ec2-user/pympler/pympler/muppy.py", line 15, in <module>
    from pympler.asizeof import _Py_TPFLAGS_HAVE_GC
  File "/home/ec2-user/pympler/pympler/asizeof.py", line 206, in <module>
    _sizeof_Cdigit = long.__itemsize__
AttributeError: type object 'long' has no attribute '__itemsize__'
```

*0.4.2: pympler works on PyPy*
```
[ec2-user@i-89b56b16 ~]$ sudo /opt/pypy/bin/pypy -m pip install pympler==0.4.2
Collecting pympler==0.4.2
Installing collected packages: pympler
  Found existing installation: Pympler 0.4.3
    Uninstalling Pympler-0.4.3:
      Successfully uninstalled Pympler-0.4.3
Successfully installed pympler-0.4.2
[ec2-user@i-89b56b16 ~]$ /opt/pypy/bin/pypy -c "import pympler.muppy"
```

*```__itemsize__``` is not available in PyPy*
```
[ec2-user@i-89b56b16 ~]$ /opt/pypy/bin/pypy -c "print dir(long)"
['__abs__', '__add__', '__and__', '__class__', '__coerce__', '__delattr__', '__div__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getnewargs__', '__gt__', '__hash__', '__hex__', '__index__', '__init__', '__int__', '__invert__', '__le__', '__long__', '__lshift__', '__lt__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__nonzero__', '__oct__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdiv__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rlshift__', '__rmod__', '__rmul__', '__ror__', '__rpow__', '__rrshift__', '__rshift__', '__rsub__', '__rtruediv__', '__rxor__', '__setattr__', '__str__', '__sub__', '__subclasshook__', '__truediv__', '__trunc__', '__xor__', 'bit_length', 'conjugate', 'denominator', 'imag', 'numerator', 'real']
```

*FYI:* https://mail.python.org/pipermail/pypy-dev/2010-December/006610.html but ```sys.getsizeof``` doesn't seem to be a solution...
```
[ec2-user@i-89b56b16 ~]$ /opt/pypy/bin/pypy -c "import sys; sys.getsizeof(long)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: sys.getsizeof() not implemented on PyPy
```

**Comment by sakurai-youhei** [comment]
*FYI 2: Gets same results even on PyPy 5.0.1*
```
[ec2-user@i-8e36c42a ~]$ /opt/pypy/bin/pypy --version
Python 2.7.10 (bbd45126bc691f669c4ebdfbd74456cd274c6b92, Mar 19 2016, 10:51:04)
[PyPy 5.0.1 with GCC 4.9.2]
[ec2-user@i-8e36c42a ~]$ /opt/pypy/bin/pypy -c "print '__itemsize__' in dir(long)"
False
[ec2-user@i-8e36c42a ~]$ /opt/pypy/bin/pypy -c "import pympler.muppy"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/pypy/site-packages/pympler/muppy.py", line 15, in <module>
    from pympler.asizeof import _Py_TPFLAGS_HAVE_GC
  File "/opt/pypy/site-packages/pympler/asizeof.py", line 206, in <module>
    _sizeof_Cdigit = long.__itemsize__
AttributeError: type object 'long' has no attribute '__itemsize__'
[ec2-user@i-8e36c42a ~]$ /opt/pypy/bin/pypy -c "import sys; sys.getsizeof(long)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: sys.getsizeof() not implemented on PyPy
```

**Comment by Pankrat** [comment]
Pympler does not support PyPy. As long as PyPy doesn't support `sys.getsizeof` I doubt that this will change.

The reason that the muppy import worked in 0.4.2 is only because muppy didn't pull in the asizeof module - which was changed for a bugfix in 0.4.3. The test suite fails on PyPy with both versions.

**Comment by Pankrat** [comment]
Please reopen the ticket if you could get value out of using `pympler.muppy` on PyPy with previous versions of Pympler. I assumed that's not the case, but I don't know your specific use case so YMMV.

**Comment by sakurai-youhei** [comment]
Thanks. You're right; I found my codes are not working even with previous version on PyPy...
```
>>>> import pympler.summary
>>>> import pympler.muppy
>>>> pympler.summary.summarize(pympler.muppy.get_objects())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/pypy/site-packages/pympler/summary.py", line 131, in summarize
    total_size[otype] = _getsizeof(o)
TypeError: sys.getsizeof() not implemented on PyPy
```
