### ISSUE TITLE
Compatibility with Django debug toolbar 2(?)

### ISSUE THREAD

**Issue by therefromhere** [pympler/pympler#96]
Just a heads up, Django debug toolbar is changing how panels are processed to be more like new-style middleware, presumably for an upcoming 2.0 release (and also dropping Python 2 support).

As a result, Pympler panel is broken vs current Django debug toolbar master, it hits this error "'NoneType' object has no attribute 'get'" because `debug_toolbar/middleware.py` expects process_request to return a response object.

Using:

django debug toolbar master (https://github.com/jazzband/django-debug-toolbar/commit/b650a33bb02651903540d726704a9143c73eda0a)
Pympler==0.7
Django==2.2.1

See simple example project that hits the bug on all requests: https://github.com/therefromhere/ddt_pympler_bug_example

Note that this doesn't affect the released version of Django debug toolbar yet.

**Comment by alexandre-paroissien** [comment]
I confirm I had this issue and another issue when updating to debug-toolbar 2.0
(https://github.com/jazzband/django-debug-toolbar/issues/1178)

django-debug-toolbar==2.0
pympler==0.7
django==2.2.2

Pympler error:
```
Traceback (most recent call last):
  File ".../lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File ".../lib/python3.7/site-packages/debug_toolbar/middleware.py", line 69, in __call__
    content_encoding = response.get("Content-Encoding", "")
AttributeError: 'NoneType' object has no attribute 'get'
```

For anyone reading this, a temporary fix is to comment lines corresponding to the errors in your settings.py:

```
DEBUG_TOOLBAR_PANELS = [
    "debug_toolbar.panels.versions.VersionsPanel",
    "debug_toolbar.panels.timer.TimerPanel",
    "debug_toolbar.panels.settings.SettingsPanel",
    "debug_toolbar.panels.headers.HeadersPanel",
    "debug_toolbar.panels.request.RequestPanel",
    "debug_toolbar.panels.sql.SQLPanel",
    "debug_toolbar.panels.staticfiles.StaticFilesPanel",
    "debug_toolbar.panels.cache.CachePanel",
    "debug_toolbar.panels.signals.SignalsPanel",
    "debug_toolbar.panels.logging.LoggingPanel",
    "debug_toolbar.panels.redirects.RedirectsPanel",
    # "debug_toolbar.panels.timer.TimerDebugPanel",  # stopped working in debug-toolbar 2.0
    # "pympler.panels.MemoryPanel",  # stopped working in debug-toolbar 2.0
]
```

**Comment by wakandan** [comment]
is there a fix for this?

**Comment by Pankrat** [comment]
Hi @therefromhere, thanks for the report and providing the setup to reproduce the issue!

I have a fix ready here https://github.com/pympler/pympler/pull/99 and tested it with your project. Unless there are concerns about the change, I'll merge it after the weekend and push out a new pympler release soon after.

While testing I realized that the sparklines for the instance counts don't work anymore (at least in my test environment). I don't have a fix for that yet and I'm tempted to just remove the feature. Please let me know if you think this is useful.

**Comment by Stark27398** [comment]
I had the same problem, try downgrading the **django-debug-toolbar** version, it fixes the problem.
Use command ```pip install django-debug-toolbar==1.11```

**Comment by Pankrat** [comment]
Pympler 0.8 should be compatible with the latest version of DDT. The changes are not backward compatible. If you're using DDT 1.11 or an older version, you should pin Pympler to version 0.7.
